### ISSUE TITLE
Getting (asn1tools.errors.CompileError) error

### ISSUE THREAD

**Issue by arsalan993** [eerimoq/asn1tools#14] opened 2018-03-16 10:50 UTC
import asn1tools
foo = asn1tools.compile_files('huawei-cdr.asn')

`asn1tools.errors.CompileError: Type 'GraphicString' not found in module 'CS-R99-R4-CHARGING'.`

**Comment by eerimoq** [comment] 2018-03-18 16:14
Fixed in 0.54.0 for BER and DER codecs.

**Closed by eerimoq** 2018-03-18 16:14 UTC

**Comment by arsalan993** [comment] 2018-03-18 16:40
kindly elaborate a bit..  i didnt get it what you mean by 0.54.0

**Comment by eerimoq** [comment] 2018-03-18 17:09
Release 0.54.0. You can install it with `pip install -U asn1tools`.

**Comment by arsalan993** [comment] 2018-03-19 07:38
I am getting this error now 
`asn1tools.codecs.ber.DecodeChoiceError`

Sir, Is it possible if you can decode this since i need this data urgently for my project.
Here is the sample code which i am running
`import asn1tools`
`foo = asn1tools.compile_files('huawei-cdr.asn')`
`f  = open('cdr.dat','r') `
`sub = f.read()`
`print foo.decode('CallEventRecord', sub)`

And here is dropbox link, folder contains two file "huawei-cdr.asn' this file is the asn mapper while "cdr.dat" file contain the encoded data. 

[ASN.1 data](https://www.dropbox.com/sh/dg5igqkfoi1jhf4/AAAjxAWTy6g18V_FjGCXBEmYa?dl=0)

**Comment by eerimoq** [comment] 2018-03-19 07:55
Looks like you are trying to decode the wrong type. Replace `CallEventRecord` with `CallEventDataFile` and it should decode successfully.

**Comment by arsalan993** [comment] 2018-03-19 07:58
I did that as well but same error

**Comment by arsalan993** [comment] 2018-03-19 07:59
I have toan decode other similar dat files as well not i can decode other similar dat files as well not jus

**Comment by eerimoq** [comment] 2018-03-19 08:05
Ahh, and open the file with `"rb"`.

**Comment by arsalan993** [comment] 2018-03-19 08:38
is it possible to convert byte array into its proper value. and how can i save an xml rather than list

**Comment by eerimoq** [comment] 2018-03-19 22:38
Try the code below with release 0.55.0 of asn1tools. Then open `cdr.xml` to see the data in XML.

``` python
import asn1tools

ber = asn1tools.compile_files('huawei-cdr.asn', 'ber')
xer = asn1tools.compile_files('huawei-cdr.asn', 'xer')

with open('cdr.dat', 'rb') as fin:
    encoded_ber = fin.read()

decoded = ber.decode('CallEventDataFile', encoded_ber)

with open('cdr.xml', 'w') as fout:
    encoded_xer = xer.encode('CallEventDataFile', decoded)
    fout.write(encoded_xer.decode('ascii'))
```

**Comment by arsalan993** [comment] 2018-03-20 05:06
Worked like charm,  Have a great day!!

**Comment by eerimoq** [comment] 2018-03-20 05:30
Have a great day yourself!! :-)

**Comment by edsase** [comment] 2019-03-31 09:59
Hi all, 
Sorry to reopen this thread again. 
Im doing a similar project like @arsalan993 and I dont get any errors when I extract the files using the script that @eerimoq  posted above. However, the extracted cdr.xml does not have key parameters like "callDuration". I thought at first it had to do with my original cdr.dat files. But this is not the case as I still get the same result (without call duration) when I used the cdr.dat files of @arsalan993 . Grateful if you could point me in the correct direction to resolve this. Thanks!

**Comment by eerimoq** [comment] 2019-04-01 06:11
Try decoding on this site: https://asn1.io/asn1playground/

If callDuration is still missing, your data does not contain callDuration.

**Comment by edsase** [comment] 2019-04-01 12:00
Hi, thanks for the link to asn1playground. My data indeed has callDuration. I have tried the data of @arsalan993 which also has callDuration, but when I run  it with the script you posted above, the callDuration does not show up. I also tried using the exact same version of asn1tools (0.54.0) as @arsalan993 and with his dataset. But still no callDuration.

**Comment by eerimoq** [comment] 2019-04-01 12:05
Pose the output from the playground here please.

**Comment by edsase** [comment] 2019-04-01 13:29
[Here's](https://drive.google.com/file/d/1w_OPjKUYmM_wW8ZHMKZEzxrnLXELdg-G/view?usp=sharing) the encoded cdr_file and [here is](https://drive.google.com/file/d/1C0qFckC_yx7htV1OoM3OPd_uyp4ZN48y/view?usp=sharing) the decoded version from playground.

**Comment by edsase** [comment] 2019-04-01 13:33
And below is an example record output from the playground and showing callDuration:
 
moCallRecord : {
      recordType moCallRecord,
      servedIMSI '16090501792314F6'H,
      servedIMEI '53650102008666F0'H,
      servedMSISDN '913282181872F0'H,
      callingNumber '913282181872F0'H,
      calledNumber '8161F0'H,
      recordingEntity '913272170808F0'H,
      mscIncomingROUTE rOUTEName : "BSC01B",
      mscOutgoingROUTE rOUTEName : "IVR01B",
      location {
        locationAreaCode '024E'H,
        cellIdentifier '2EF3'H
      },
      basicService teleservice : '11'H,
      msClassmark '505881'H,
      seizureTime '1902010004552B0000'H,
      answerTime '1902010004562B0000'H,
      releaseTime '1902010005012B0000'H,
      callDuration 5,
      radioChanRequested dualFullRatePreferred,
      radioChanUsed fullRate,
      causeForTerm normalRelease,
      diagnostics gsm0408Cause : 144,
      callReference '03EF035D93CC'H,
      additionalChgInfo {
        chargeIndicator charge
      }

**Comment by eerimoq** [comment] 2019-04-01 17:21
Should be fixed in version 0.146.1, available on PyPI!

However, the BER decoder is still not fully complient with the ASN.1 standard, but I think it works in practice. ASN.1 standard allows SET members in any order, but asntools can only decode them if they are sorted.

**Comment by lmasarati** [comment] 2021-01-31 15:38
> The ASN.1 standard allows SET members in any order, but asn1tools can only decode them if they are sorted.

Hi Erik, I'm having this problem with Huawei BER encoded CDRs that have non-consecutive tag values.
I solved redefining the asn1tools.codecs.ber.MembersType.decode() method with a local version which has a 'while (offset < end_offset):' loop around the 'for member in self.root_members:' loop. It's not efficient, I know, but solved the problem with 2 additional cycles...

**Comment by eerimoq** [comment] 2021-01-31 15:43
Sorry, I don't have time to help.

**Comment by lmasarati** [comment] 2021-02-01 08:12
> Sorry, I don't have time to help.

It was intended as a comment about your statement...
Actually, I was not asking for help, but offering a quick solution to anyone who's having the same problem.
Thanks.

**Comment by eerimoq** [comment] 2021-02-01 09:23
Sorry, didn't read carefully. Almost everyone want help :P

**Comment by Finndersen** [comment] 2021-02-22 02:04
hey @eerimoq @Immasarti I have reworked ber.MembersType.decode() to add support for SET members in any order, and also improved decode performance at the same time. See my fork: https://github.com/Finndersen/asn1tools There is also an open pull request

**Comment by lmasarati** [comment] 2021-02-22 08:29
Thanks @Finndersen, very appreciated.

**Comment by Finndersen** [comment] 2021-02-22 08:30
Does it work as expected for your use case?

**Comment by Finndersen** [comment] 2021-02-22 08:30
I have merged in changes

**Comment by eerimoq** [comment] 2021-02-22 08:36
@Finndersen Pushing tags automatically publishes to PyPI. So it's easy to do.

**Comment by lmasarati** [comment] 2021-02-22 08:58
> Does it work as expected for your use case?

I confirm, yes.
Thanks.

**Comment by Finndersen** [comment] 2021-02-23 04:26
@eerimoq  I just manually created new release, will that also publish to PyPI?

**Comment by eerimoq** [comment] 2021-02-23 07:20
@Finndersen You can find the logs from the tagged jobs here: https://github.com/eerimoq/asn1tools/actions/runs/591394281
A new release was published to PyPI. However, I forgot to tell you that the version in `asn1tools/version.py` should be bumped and committed before tagging with the same version. So please do that as well, otherwise `asn1tools --version` will show the older version.
